# Generated by Django 4.2 on 2023-04-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_alter_category_options_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
